name: Deploy
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: safe-starfish-86-v2
          entrypoint: main.ts
          import-map: deno.json
